// AUTO-GENERATED — Run: npx ts-node --skip-project scripts/seed-hierarchy.ts
import { createClient } from '@supabase/supabase-js'
import * as dotenv from 'dotenv'
dotenv.config({ path: '.env.local' })

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

const SUBTOPICS = [
  { ref: 'C1.1', topicRef: 'C1', name: 'Types of number', e_only: false },
  { ref: 'C1.2', topicRef: 'C1', name: 'Sets', e_only: false },
  { ref: 'C1.3', topicRef: 'C1', name: 'Powers and roots', e_only: false },
  { ref: 'C1.4', topicRef: 'C1', name: 'Fractions, decimals and percentages', e_only: false },
  { ref: 'C1.5', topicRef: 'C1', name: 'Ordering', e_only: false },
  { ref: 'C1.6', topicRef: 'C1', name: 'The four operations', e_only: false },
  { ref: 'C1.7', topicRef: 'C1', name: 'Indices I', e_only: false },
  { ref: 'C1.8', topicRef: 'C1', name: 'Standard form', e_only: false },
  { ref: 'C1.9', topicRef: 'C1', name: 'Estimation', e_only: false },
  { ref: 'C1.10', topicRef: 'C1', name: 'Limits of accuracy', e_only: false },
  { ref: 'C1.11', topicRef: 'C1', name: 'Ratio and proportion', e_only: false },
  { ref: 'C1.12', topicRef: 'C1', name: 'Rates', e_only: false },
  { ref: 'C1.13', topicRef: 'C1', name: 'Percentages', e_only: false },
  { ref: 'C1.14', topicRef: 'C1', name: 'Using a calculator', e_only: false },
  { ref: 'C1.15', topicRef: 'C1', name: 'Time', e_only: false },
  { ref: 'C1.16', topicRef: 'C1', name: 'Money', e_only: false },
  { ref: 'E1.17', topicRef: 'C1', name: 'Exponential growth and decay', e_only: true },
  { ref: 'E1.18', topicRef: 'C1', name: 'Surds', e_only: true },
  { ref: 'C2.1', topicRef: 'C2', name: 'Introduction to algebra', e_only: false },
  { ref: 'C2.2', topicRef: 'C2', name: 'Algebraic manipulation', e_only: false },
  { ref: 'E2.3', topicRef: 'C2', name: 'Algebraic fractions', e_only: true },
  { ref: 'C2.4', topicRef: 'C2', name: 'Indices II', e_only: false },
  { ref: 'C2.5', topicRef: 'C2', name: 'Equations', e_only: false },
  { ref: 'C2.6', topicRef: 'C2', name: 'Inequalities', e_only: false },
  { ref: 'C2.7', topicRef: 'C2', name: 'Sequences', e_only: false },
  { ref: 'E2.8', topicRef: 'C2', name: 'Proportion', e_only: true },
  { ref: 'C2.9', topicRef: 'C2', name: 'Graphs in practical situations', e_only: false },
  { ref: 'C2.10', topicRef: 'C2', name: 'Graphs of functions', e_only: false },
  { ref: 'C2.11', topicRef: 'C2', name: 'Sketching curves', e_only: false },
  { ref: 'E2.12', topicRef: 'C2', name: 'Differentiation', e_only: true },
  { ref: 'E2.13', topicRef: 'C2', name: 'Functions', e_only: true },
  { ref: 'C3.1', topicRef: 'C3', name: 'Coordinates', e_only: false },
  { ref: 'C3.2', topicRef: 'C3', name: 'Drawing linear graphs', e_only: false },
  { ref: 'C3.3', topicRef: 'C3', name: 'Gradient of linear graphs', e_only: false },
  { ref: 'E3.4', topicRef: 'C3', name: 'Length and midpoint', e_only: true },
  { ref: 'C3.5', topicRef: 'C3', name: 'Equations of linear graphs', e_only: false },
  { ref: 'C3.6', topicRef: 'C3', name: 'Parallel lines', e_only: false },
  { ref: 'E3.7', topicRef: 'C3', name: 'Perpendicular lines', e_only: true },
  { ref: 'C4.1', topicRef: 'C4', name: 'Geometrical terms', e_only: false },
  { ref: 'C4.2', topicRef: 'C4', name: 'Geometrical constructions', e_only: false },
  { ref: 'C4.3', topicRef: 'C4', name: 'Scale drawings', e_only: false },
  { ref: 'C4.4', topicRef: 'C4', name: 'Similarity', e_only: false },
  { ref: 'C4.5', topicRef: 'C4', name: 'Symmetry', e_only: false },
  { ref: 'C4.6', topicRef: 'C4', name: 'Angles', e_only: false },
  { ref: 'C4.7', topicRef: 'C4', name: 'Circle theorems I', e_only: false },
  { ref: 'E4.8', topicRef: 'C4', name: 'Circle theorems II', e_only: true },
  { ref: 'C5.1', topicRef: 'C5', name: 'Units of measure', e_only: false },
  { ref: 'C5.2', topicRef: 'C5', name: 'Area and perimeter', e_only: false },
  { ref: 'C5.3', topicRef: 'C5', name: 'Circles, arcs and sectors', e_only: false },
  { ref: 'C5.4', topicRef: 'C5', name: 'Surface area and volume', e_only: false },
  { ref: 'C5.5', topicRef: 'C5', name: 'Compound shapes and parts of shapes', e_only: false },
  { ref: 'C6.1', topicRef: 'C6', name: "Pythagoras' theorem", e_only: false },
  { ref: 'C6.2', topicRef: 'C6', name: 'Right-angled triangles', e_only: false },
  { ref: 'E6.3', topicRef: 'C6', name: 'Exact trigonometric values', e_only: true },
  { ref: 'E6.4', topicRef: 'C6', name: 'Trigonometric functions', e_only: true },
  { ref: 'E6.5', topicRef: 'C6', name: 'Non-right-angled triangles', e_only: true },
  { ref: 'E6.6', topicRef: 'C6', name: "Pythagoras' theorem and trigonometry in 3D", e_only: true },
  { ref: 'C7.1', topicRef: 'C7', name: 'Transformations', e_only: false },
  { ref: 'E7.2', topicRef: 'C7', name: 'Vectors in two dimensions', e_only: true },
  { ref: 'E7.3', topicRef: 'C7', name: 'Magnitude of a vector', e_only: true },
  { ref: 'E7.4', topicRef: 'C7', name: 'Vector geometry', e_only: true },
  { ref: 'C8.1', topicRef: 'C8', name: 'Introduction to probability', e_only: false },
  { ref: 'C8.2', topicRef: 'C8', name: 'Relative and expected frequencies', e_only: false },
  { ref: 'C8.3', topicRef: 'C8', name: 'Probability of combined events', e_only: false },
  { ref: 'E8.4', topicRef: 'C8', name: 'Conditional probability', e_only: true },
  { ref: 'C9.1', topicRef: 'C9', name: 'Classifying statistical data', e_only: false },
  { ref: 'C9.2', topicRef: 'C9', name: 'Interpreting statistical data', e_only: false },
  { ref: 'C9.3', topicRef: 'C9', name: 'Averages and range', e_only: false },
  { ref: 'C9.4', topicRef: 'C9', name: 'Statistical charts and diagrams', e_only: false },
  { ref: 'C9.5', topicRef: 'C9', name: 'Scatter diagrams', e_only: false },
  { ref: 'E9.6', topicRef: 'C9', name: 'Cumulative frequency diagrams', e_only: true },
  { ref: 'E9.7', topicRef: 'C9', name: 'Histograms', e_only: true },
]

const SUB_SUBTOPICS = [
  { subtopicRef: 'C1.1', ref: 'C1.1.1', name: 'Number: Writing words in figures', e_only: false },
  { subtopicRef: 'C1.1', ref: 'C1.1.2', name: 'Number: Writing figures in words', e_only: false },
  { subtopicRef: 'C1.1', ref: 'C1.1.3', name: 'Number: prime numbers', e_only: false },
  { subtopicRef: 'C1.1', ref: 'C1.1.4', name: 'Number: square numbers', e_only: false },
  { subtopicRef: 'C1.1', ref: 'C1.1.5', name: 'Number: cube numbers', e_only: false },
  { subtopicRef: 'C1.1', ref: 'C1.1.6', name: 'Number: product of primes', e_only: false },
  { subtopicRef: 'C1.1', ref: 'C1.1.7', name: 'Number: common factors/HCF', e_only: false },
  { subtopicRef: 'C1.1', ref: 'C1.1.8', name: 'Number: common multiples/LCM', e_only: false },
  { subtopicRef: 'C1.1', ref: 'C1.1.9', name: 'Number: rational/irrational', e_only: false },
  { subtopicRef: 'C1.1', ref: 'C1.1.10', name: 'Fractions: reciprocal', e_only: false },
  { subtopicRef: 'C1.2', ref: 'C1.2.1', name: 'Set notation', e_only: false },
  { subtopicRef: 'C1.2', ref: 'C1.2.2', name: 'Venn Diagrams', e_only: false },
  { subtopicRef: 'C1.2', ref: 'C1.2.3', name: 'Sets: union and intersection', e_only: false },
  { subtopicRef: 'C1.2', ref: 'C1.2.4', name: 'Sets: complement', e_only: false },
  { subtopicRef: 'C1.2', ref: 'C1.2.5', name: 'Sets: subsets and number of elements', e_only: true },
  { subtopicRef: 'C1.3', ref: 'C1.3.1', name: 'Number: square numbers', e_only: false },
  { subtopicRef: 'C1.3', ref: 'C1.3.2', name: 'Number: squaring a number', e_only: false },
  { subtopicRef: 'C1.3', ref: 'C1.3.3', name: 'Number: square root', e_only: false },
  { subtopicRef: 'C1.3', ref: 'C1.3.4', name: 'Number: cube numbers', e_only: false },
  { subtopicRef: 'C1.3', ref: 'C1.3.5', name: 'Number: cubing a number', e_only: false },
  { subtopicRef: 'C1.3', ref: 'C1.3.6', name: 'Number: cube root', e_only: false },
  { subtopicRef: 'C1.3', ref: 'C1.3.7', name: 'Powers and roots: other powers and roots', e_only: false },
  { subtopicRef: 'C1.4', ref: 'C1.4.1', name: 'FDP: percentages to decimals', e_only: false },
  { subtopicRef: 'C1.4', ref: 'C1.4.2', name: 'FDP: percentages to fractions', e_only: false },
  { subtopicRef: 'C1.4', ref: 'C1.4.3', name: 'FDP: decimals to fractions', e_only: false },
  { subtopicRef: 'C1.4', ref: 'C1.4.4', name: 'FDP: decimals to fractions (calc)', e_only: false },
  { subtopicRef: 'C1.4', ref: 'C1.4.5', name: 'FDP: decimals to percentages', e_only: false },
  { subtopicRef: 'C1.4', ref: 'C1.4.6', name: 'FDP: fractions to percentages', e_only: false },
  { subtopicRef: 'C1.4', ref: 'C1.4.7', name: 'FDP: fractions to decimals', e_only: false },
  { subtopicRef: 'C1.4', ref: 'C1.4.8', name: 'FDP: fractions to decimals (calc)', e_only: false },
  { subtopicRef: 'C1.4', ref: 'C1.4.9', name: 'FDP: key equivalents', e_only: false },
  { subtopicRef: 'C1.4', ref: 'C1.4.10', name: 'Fractions: simplifying', e_only: false },
  { subtopicRef: 'C1.4', ref: 'C1.4.11', name: 'Fractions: equivalent', e_only: false },
  { subtopicRef: 'C1.4', ref: 'C1.4.12', name: 'Fractions: improper to mixed number', e_only: false },
  { subtopicRef: 'C1.4', ref: 'C1.4.13', name: 'Fractions: mixed number to improper', e_only: false },
  { subtopicRef: 'C1.4', ref: 'C1.4.14', name: 'Decimals: recurring decimals', e_only: true },
  { subtopicRef: 'C1.5', ref: 'C1.5.1', name: 'Number: ordering numbers', e_only: false },
  { subtopicRef: 'C1.5', ref: 'C1.5.2', name: 'Decimals: ordering', e_only: false },
  { subtopicRef: 'C1.5', ref: 'C1.5.3', name: 'Fractions: ordering', e_only: false },
  { subtopicRef: 'C1.5', ref: 'C1.5.4', name: 'FDP: ordering', e_only: false },
  { subtopicRef: 'C1.5', ref: 'C1.5.5', name: 'Negatives: ordering', e_only: false },
  { subtopicRef: 'C1.6', ref: 'C1.6.1', name: 'Addition: column method', e_only: false },
  { subtopicRef: 'C1.6', ref: 'C1.6.2', name: 'Subtraction', e_only: false },
  { subtopicRef: 'C1.6', ref: 'C1.6.3', name: 'Multiplication: column method', e_only: false },
  { subtopicRef: 'C1.6', ref: 'C1.6.4', name: 'Division: short division', e_only: false },
  { subtopicRef: 'C1.6', ref: 'C1.6.5', name: 'Number: BODMAS (order of operations)', e_only: false },
  { subtopicRef: 'C1.6', ref: 'C1.6.6', name: 'Negatives: addition/subtractions', e_only: false },
  { subtopicRef: 'C1.6', ref: 'C1.6.7', name: 'Negatives: multiplication', e_only: false },
  { subtopicRef: 'C1.6', ref: 'C1.6.8', name: 'Negatives: division', e_only: false },
  { subtopicRef: 'C1.6', ref: 'C1.6.9', name: 'Fractions: addition same denominator', e_only: false },
  { subtopicRef: 'C1.6', ref: 'C1.6.10', name: 'Fractions: addition diff denominators', e_only: false },
  { subtopicRef: 'C1.6', ref: 'C1.6.11', name: 'Fractions: multiplication', e_only: false },
  { subtopicRef: 'C1.6', ref: 'C1.6.12', name: 'Fractions: division', e_only: false },
  { subtopicRef: 'C1.6', ref: 'C1.6.13', name: 'Decimals: addition', e_only: false },
  { subtopicRef: 'C1.6', ref: 'C1.6.14', name: 'Decimals: subtraction', e_only: false },
  { subtopicRef: 'C1.6', ref: 'C1.6.15', name: 'Decimals: multiplying', e_only: false },
  { subtopicRef: 'C1.6', ref: 'C1.6.16', name: 'Division: by decimals', e_only: false },
  { subtopicRef: 'C1.7', ref: 'C1.7.1', name: 'Indices (numerical)', e_only: false },
  { subtopicRef: 'C1.7', ref: 'C1.7.2', name: 'Indices: laws of', e_only: false },
  { subtopicRef: 'C1.7', ref: 'C1.7.3', name: 'Indices: negative', e_only: false },
  { subtopicRef: 'C1.7', ref: 'C1.7.4', name: 'Indices: fractional', e_only: true },
  { subtopicRef: 'C1.8', ref: 'C1.8.1', name: 'Standard form', e_only: false },
  { subtopicRef: 'C1.8', ref: 'C1.8.2', name: 'Standard form: addition', e_only: false },
  { subtopicRef: 'C1.8', ref: 'C1.8.3', name: 'Standard form: multiplication', e_only: false },
  { subtopicRef: 'C1.8', ref: 'C1.8.4', name: 'Standard form: division', e_only: false },
  { subtopicRef: 'C1.9', ref: 'C1.9.1', name: 'Number: estimation', e_only: false },
  { subtopicRef: 'C1.9', ref: 'C1.9.2', name: 'Sensible estimates', e_only: false },
  { subtopicRef: 'C1.9', ref: 'C1.9.3', name: 'Rounding: to whole numbers', e_only: false },
  { subtopicRef: 'C1.9', ref: 'C1.9.4', name: 'Rounding: to nearest 10', e_only: false },
  { subtopicRef: 'C1.9', ref: 'C1.9.5', name: 'Rounding: to nearest 100', e_only: false },
  { subtopicRef: 'C1.9', ref: 'C1.9.6', name: 'Rounding: to decimal places', e_only: false },
  { subtopicRef: 'C1.9', ref: 'C1.9.7', name: 'Rounding: significant figures', e_only: false },
  { subtopicRef: 'C1.10', ref: 'C1.10.1', name: 'Limits of accuracy', e_only: false },
  { subtopicRef: 'C1.10', ref: 'C1.10.2', name: 'Limits of accuracy: applying', e_only: true },
  { subtopicRef: 'C1.10', ref: 'C1.10.3', name: 'Error Intervals', e_only: true },
  { subtopicRef: 'C1.11', ref: 'C1.11.1', name: 'Ratio: simplifying', e_only: false },
  { subtopicRef: 'C1.11', ref: 'C1.11.2', name: 'Ratio: sharing the total', e_only: false },
  { subtopicRef: 'C1.11', ref: 'C1.11.3', name: 'Ratio: given one value', e_only: false },
  { subtopicRef: 'C1.11', ref: 'C1.11.4', name: 'Ratio: given two ratios', e_only: true },
  { subtopicRef: 'C1.11', ref: 'C1.11.5', name: 'Ratio: difference between', e_only: true },
  { subtopicRef: 'C1.11', ref: 'C1.11.6', name: 'Ratio: express as fractions or %', e_only: true },
  { subtopicRef: 'C1.11', ref: 'C1.11.7', name: 'Ratio: expressing as 1:n', e_only: true },
  { subtopicRef: 'C1.11', ref: 'C1.11.8', name: 'Ratio: equations/ratios', e_only: true },
  { subtopicRef: 'C1.11', ref: 'C1.11.9', name: 'Ratio: solving problems 1', e_only: true },
  { subtopicRef: 'C1.11', ref: 'C1.11.10', name: 'Proportion: direct', e_only: false },
  { subtopicRef: 'C1.11', ref: 'C1.11.11', name: 'Proportion: inverse', e_only: true },
  { subtopicRef: 'C1.11', ref: 'C1.11.12', name: 'Proportion: unitary method', e_only: false },
  { subtopicRef: 'C1.11', ref: 'C1.11.13', name: 'Proportion: recipes', e_only: false },
  { subtopicRef: 'C1.11', ref: 'C1.11.14', name: 'Number: best buys', e_only: false },
  { subtopicRef: 'C1.11', ref: 'C1.11.15', name: 'Scales and maps', e_only: false },
  { subtopicRef: 'C1.12', ref: 'C1.12.1', name: 'Speed, distance and time', e_only: false },
  { subtopicRef: 'C1.12', ref: 'C1.12.2', name: 'Number: currency', e_only: false },
  { subtopicRef: 'C1.12', ref: 'C1.12.3', name: 'Pressure', e_only: false },
  { subtopicRef: 'C1.12', ref: 'C1.12.4', name: 'Density', e_only: false },
  { subtopicRef: 'C1.12', ref: 'C1.12.5', name: 'Population Density', e_only: false },
  { subtopicRef: 'C1.12', ref: 'C1.12.6', name: 'Rates: flow rates', e_only: false },
  { subtopicRef: 'C1.12', ref: 'C1.12.7', name: 'Rates: fuel consumption', e_only: false },
  { subtopicRef: 'C1.12', ref: 'C1.12.8', name: 'Money: Wages', e_only: false },
  { subtopicRef: 'C1.13', ref: 'C1.13.1', name: 'Percentages: of an amount (non-calc)', e_only: false },
  { subtopicRef: 'C1.13', ref: 'C1.13.2', name: 'Percentages: of an amount (calc)', e_only: false },
  { subtopicRef: 'C1.13', ref: 'C1.13.3', name: 'Percentages: expressing as', e_only: false },
  { subtopicRef: 'C1.13', ref: 'C1.13.4', name: 'Percentages: change', e_only: false },
  { subtopicRef: 'C1.13', ref: 'C1.13.5', name: 'Percentages: increasing/decreasing', e_only: false },
  { subtopicRef: 'C1.13', ref: 'C1.13.6', name: 'Percentages: multipliers', e_only: false },
  { subtopicRef: 'C1.13', ref: 'C1.13.7', name: 'Percentages: simple interest', e_only: false },
  { subtopicRef: 'C1.13', ref: 'C1.13.8', name: 'Percentages: compound interest', e_only: false },
  { subtopicRef: 'C1.13', ref: 'C1.13.9', name: 'Percentages: reverse', e_only: true },
  { subtopicRef: 'C1.13', ref: 'C1.13.10', name: 'Money: Discounts', e_only: false },
  { subtopicRef: 'C1.13', ref: 'C1.13.11', name: 'Money: VAT', e_only: false },
  { subtopicRef: 'C1.13', ref: 'C1.13.12', name: 'Money: Profit', e_only: false },
  { subtopicRef: 'C1.13', ref: 'C1.13.13', name: 'Money: Tax', e_only: false },
  { subtopicRef: 'C1.14', ref: 'C1.14.1', name: 'Use of a calculator', e_only: false },
  { subtopicRef: 'C1.15', ref: 'C1.15.1', name: 'Time: calculations', e_only: false },
  { subtopicRef: 'C1.15', ref: 'C1.15.2', name: 'Tables: timetables', e_only: false },
  { subtopicRef: 'C1.15', ref: 'C1.15.3', name: 'Time: time zones and local times', e_only: false },
  { subtopicRef: 'C1.16', ref: 'C1.16.1', name: 'Money: Coins', e_only: false },
  { subtopicRef: 'C1.16', ref: 'C1.16.2', name: 'Money: Change', e_only: false },
  { subtopicRef: 'C1.16', ref: 'C1.16.3', name: 'Money: Buying', e_only: false },
  { subtopicRef: 'C1.16', ref: 'C1.16.4', name: 'Money: Regular Payments', e_only: false },
  { subtopicRef: 'C1.16', ref: 'C1.16.5', name: 'Money: Bills', e_only: false },
  { subtopicRef: 'C1.16', ref: 'C1.16.6', name: 'Money: Discounts', e_only: false },
  { subtopicRef: 'C1.16', ref: 'C1.16.7', name: 'Money: VAT', e_only: false },
  { subtopicRef: 'C1.16', ref: 'C1.16.8', name: 'Money: Wages', e_only: false },
  { subtopicRef: 'C1.16', ref: 'C1.16.9', name: 'Money: Bank Statements', e_only: false },
  { subtopicRef: 'C1.16', ref: 'C1.16.10', name: 'Money: Tax', e_only: false },
  { subtopicRef: 'C1.16', ref: 'C1.16.11', name: 'Money: Cost per kg', e_only: false },
  { subtopicRef: 'C1.16', ref: 'C1.16.12', name: 'Money: Cost per litre', e_only: false },
  { subtopicRef: 'C1.16', ref: 'C1.16.13', name: 'Money: Cost per metre', e_only: false },
  { subtopicRef: 'C1.16', ref: 'C1.16.14', name: 'Money: Reading meters', e_only: false },
  { subtopicRef: 'C1.16', ref: 'C1.16.15', name: 'Money: Profit', e_only: false },
  { subtopicRef: 'C1.16', ref: 'C1.16.16', name: 'Money: Greatest/Maximum', e_only: false },
  { subtopicRef: 'C1.16', ref: 'C1.16.17', name: 'Money: Estimation', e_only: false },
  { subtopicRef: 'C1.16', ref: 'C1.16.18', name: 'Money: Midpoint', e_only: false },
  { subtopicRef: 'C1.16', ref: 'C1.16.19', name: 'Money: Proportion', e_only: false },
  { subtopicRef: 'C1.16', ref: 'C1.16.20', name: 'Number: currency', e_only: false },
  { subtopicRef: 'E1.17', ref: 'E1.17.1', name: 'Exponential growth and decay', e_only: true },
  { subtopicRef: 'E1.17', ref: 'E1.17.2', name: 'Percentages: multipliers', e_only: true },
  { subtopicRef: 'E1.17', ref: 'E1.17.3', name: 'Percentages: compound interest', e_only: true },
  { subtopicRef: 'E1.17', ref: 'E1.17.4', name: 'Geometric progressions', e_only: true },
  { subtopicRef: 'E1.18', ref: 'E1.18.1', name: 'Surds: intro, rules, simplifying', e_only: true },
  { subtopicRef: 'E1.18', ref: 'E1.18.2', name: 'Surds: addition/subtraction', e_only: true },
  { subtopicRef: 'E1.18', ref: 'E1.18.3', name: 'Surds: rationalising denominators', e_only: true },
  { subtopicRef: 'E1.18', ref: 'E1.18.4', name: 'Surds: expanding brackets', e_only: true },
  { subtopicRef: 'C2.1', ref: 'C2.1.1', name: 'Algebra: notation', e_only: false },
  { subtopicRef: 'C2.1', ref: 'C2.1.2', name: 'Algebra: substitution', e_only: false },
  { subtopicRef: 'C2.1', ref: 'C2.1.3', name: 'Algebra: expressions forming', e_only: false },
  { subtopicRef: 'C2.1', ref: 'C2.1.4', name: 'Function Machines', e_only: false },
  { subtopicRef: 'C2.2', ref: 'C2.2.1', name: 'Algebra: collecting like terms', e_only: false },
  { subtopicRef: 'C2.2', ref: 'C2.2.2', name: 'Algebra: expanding brackets', e_only: false },
  { subtopicRef: 'C2.2', ref: 'C2.2.3', name: 'Algebra: expanding two brackets', e_only: false },
  { subtopicRef: 'C2.2', ref: 'C2.2.4', name: 'Algebra: expanding three brackets', e_only: true },
  { subtopicRef: 'C2.2', ref: 'C2.2.5', name: 'Factorisation', e_only: false },
  { subtopicRef: 'C2.2', ref: 'C2.2.6', name: 'Factorisation: brackets', e_only: false },
  { subtopicRef: 'C2.2', ref: 'C2.2.7', name: 'Factorisation: quadratics', e_only: true },
  { subtopicRef: 'C2.2', ref: 'C2.2.8', name: 'Factorisation: quadratics harder', e_only: true },
  { subtopicRef: 'C2.2', ref: 'C2.2.9', name: 'Factorisation: splitting the middle', e_only: true },
  { subtopicRef: 'C2.2', ref: 'C2.2.10', name: 'Factorisation: difference of 2 squares', e_only: true },
  { subtopicRef: 'C2.2', ref: 'C2.2.11', name: 'Algebra: completing the square', e_only: true },
  { subtopicRef: 'E2.3', ref: 'E2.3.1', name: 'Algebraic fractions: simplifying', e_only: true },
  { subtopicRef: 'E2.3', ref: 'E2.3.2', name: 'Algebraic fractions: addition', e_only: true },
  { subtopicRef: 'E2.3', ref: 'E2.3.3', name: 'Algebraic fractions: multiplication', e_only: true },
  { subtopicRef: 'E2.3', ref: 'E2.3.4', name: 'Algebraic fractions: division', e_only: true },
  { subtopicRef: 'C2.4', ref: 'C2.4.1', name: 'Algebra: indices', e_only: false },
  { subtopicRef: 'C2.4', ref: 'C2.4.2', name: 'Indices: laws of', e_only: false },
  { subtopicRef: 'C2.4', ref: 'C2.4.3', name: 'Indices: negative', e_only: false },
  { subtopicRef: 'C2.4', ref: 'C2.4.4', name: 'Indices: fractional', e_only: true },
  { subtopicRef: 'C2.5', ref: 'C2.5.1', name: 'Equations: forming', e_only: false },
  { subtopicRef: 'C2.5', ref: 'C2.5.2', name: 'Equations: solving', e_only: false },
  { subtopicRef: 'C2.5', ref: 'C2.5.3', name: 'Equations: involving fractions', e_only: false },
  { subtopicRef: 'C2.5', ref: 'C2.5.4', name: 'Equations: fractional advanced', e_only: true },
  { subtopicRef: 'C2.5', ref: 'C2.5.5', name: 'Equations: cross multiplication', e_only: true },
  { subtopicRef: 'C2.5', ref: 'C2.5.6', name: 'Equations: letters both sides', e_only: false },
  { subtopicRef: 'C2.5', ref: 'C2.5.7', name: 'Equations: x squared', e_only: true },
  { subtopicRef: 'C2.5', ref: 'C2.5.8', name: 'Simultaneous equations (elimination)', e_only: false },
  { subtopicRef: 'C2.5', ref: 'C2.5.9', name: 'Simultaneous equations (substitution)', e_only: false },
  { subtopicRef: 'C2.5', ref: 'C2.5.10', name: 'Simultaneous equations (advanced)', e_only: true },
  { subtopicRef: 'C2.5', ref: 'C2.5.11', name: 'Quadratics: solving (factorising)', e_only: true },
  { subtopicRef: 'C2.5', ref: 'C2.5.12', name: 'Quadratics: formula', e_only: true },
  { subtopicRef: 'C2.5', ref: 'C2.5.13', name: 'Quadratics: completing the square', e_only: true },
  { subtopicRef: 'C2.5', ref: 'C2.5.14', name: 'Algebra: changing the subject', e_only: false },
  { subtopicRef: 'C2.5', ref: 'C2.5.15', name: 'Algebra: changing the subject advanced', e_only: true },
  { subtopicRef: 'C2.6', ref: 'C2.6.1', name: 'Inequalities', e_only: false },
  { subtopicRef: 'C2.6', ref: 'C2.6.2', name: 'Inequalities on a number line', e_only: false },
  { subtopicRef: 'C2.6', ref: 'C2.6.3', name: 'Inequalities: solving (one sign)', e_only: false },
  { subtopicRef: 'C2.6', ref: 'C2.6.4', name: 'Inequalities: solving (two signs)', e_only: true },
  { subtopicRef: 'C2.6', ref: 'C2.6.5', name: 'Inequalities: graphical y>a or x>a', e_only: true },
  { subtopicRef: 'C2.6', ref: 'C2.6.6', name: 'Inequalities: graphical y>x+a', e_only: true },
  { subtopicRef: 'C2.6', ref: 'C2.6.7', name: 'Inequalities: regions', e_only: true },
  { subtopicRef: 'C2.6', ref: 'C2.6.8', name: 'Inequalities: quadratic', e_only: true },
  { subtopicRef: 'C2.6', ref: 'C2.6.9', name: 'Forming quadratic inequalities', e_only: true },
  { subtopicRef: 'C2.7', ref: 'C2.7.1', name: 'Sequences: missing terms', e_only: false },
  { subtopicRef: 'C2.7', ref: 'C2.7.2', name: 'Sequences: describing rules', e_only: false },
  { subtopicRef: 'C2.7', ref: 'C2.7.3', name: 'Sequences: nth term', e_only: false },
  { subtopicRef: 'C2.7', ref: 'C2.7.4', name: 'Sequences: nth term fractional', e_only: true },
  { subtopicRef: 'C2.7', ref: 'C2.7.5', name: 'Sequences: patterns', e_only: false },
  { subtopicRef: 'C2.7', ref: 'C2.7.6', name: 'Sequences: Fibonacci', e_only: false },
  { subtopicRef: 'C2.7', ref: 'C2.7.7', name: 'Quadratic nth term V1', e_only: true },
  { subtopicRef: 'C2.7', ref: 'C2.7.8', name: 'Quadratic nth term V2', e_only: true },
  { subtopicRef: 'C2.7', ref: 'C2.7.9', name: 'Quadratic nth term V3', e_only: true },
  { subtopicRef: 'C2.7', ref: 'C2.7.10', name: 'Arithmetic progressions', e_only: true },
  { subtopicRef: 'C2.7', ref: 'C2.7.11', name: 'Geometric progressions', e_only: true },
  { subtopicRef: 'E2.8', ref: 'E2.8.1', name: 'Proportion: direct', e_only: true },
  { subtopicRef: 'E2.8', ref: 'E2.8.2', name: 'Proportion: inverse', e_only: true },
  { subtopicRef: 'E2.8', ref: 'E2.8.3', name: 'Proportion: unitary method', e_only: true },
  { subtopicRef: 'E2.8', ref: 'E2.8.4', name: 'Proportion: Graphs', e_only: true },
  { subtopicRef: 'E2.8', ref: 'E2.8.5', name: 'Proportion: Time', e_only: true },
  { subtopicRef: 'E2.8', ref: 'E2.8.6', name: 'Proportion: square and cube', e_only: true },
  { subtopicRef: 'C2.9', ref: 'C2.9.1', name: 'Graphs: distance-time graphs', e_only: false },
  { subtopicRef: 'C2.9', ref: 'C2.9.2', name: 'Graphs: real life linear graphs', e_only: false },
  { subtopicRef: 'C2.9', ref: 'C2.9.3', name: 'Graphs: filling containers', e_only: true },
  { subtopicRef: 'C2.9', ref: 'C2.9.4', name: 'Graphs: conversion graphs (draw)', e_only: false },
  { subtopicRef: 'C2.9', ref: 'C2.9.5', name: 'Graphs: conversion graphs (interpret)', e_only: false },
  { subtopicRef: 'C2.9', ref: 'C2.9.6', name: 'Area under a Graph', e_only: true },
  { subtopicRef: 'C2.9', ref: 'C2.9.7', name: 'Instantaneous Rate of Change', e_only: true },
  { subtopicRef: 'C2.9', ref: 'C2.9.8', name: 'Average Rate of Change', e_only: true },
  { subtopicRef: 'C2.9', ref: 'C2.9.9', name: 'Kinematics formulae', e_only: true },
  { subtopicRef: 'C2.10', ref: 'C2.10.1', name: 'Linear graphs: drawing (xy table)', e_only: false },
  { subtopicRef: 'C2.10', ref: 'C2.10.2', name: 'Quadratic graphs: drawing', e_only: false },
  { subtopicRef: 'C2.10', ref: 'C2.10.3', name: 'Quadratics: solving graphically', e_only: false },
  { subtopicRef: 'C2.10', ref: 'C2.10.4', name: 'Types of graph: reciprocal', e_only: false },
  { subtopicRef: 'C2.10', ref: 'C2.10.5', name: 'Graphs: exponential growth and decay', e_only: true },
  { subtopicRef: 'C2.11', ref: 'C2.11.1', name: 'Quadratic graphs: sketching key points', e_only: false },
  { subtopicRef: 'C2.11', ref: 'C2.11.2', name: 'Quadratic graphs: line of symmetry', e_only: false },
  { subtopicRef: 'C2.11', ref: 'C2.11.3', name: 'Quadratic graphs: finding turning point', e_only: true },
  { subtopicRef: 'C2.11', ref: 'C2.11.4', name: 'Types of graph: cubics', e_only: true },
  { subtopicRef: 'C2.11', ref: 'C2.11.5', name: 'Types of graph: reciprocal', e_only: true },
  { subtopicRef: 'C2.11', ref: 'C2.11.6', name: 'Types of graph: exponential', e_only: true },
  { subtopicRef: 'E2.12', ref: 'E2.12.1', name: 'Instantaneous Rate of Change', e_only: true },
  { subtopicRef: 'E2.12', ref: 'E2.12.2', name: 'Average Rate of Change', e_only: true },
  { subtopicRef: 'E2.12', ref: 'E2.12.3', name: 'Differentiation: gradients and tangents', e_only: true },
  { subtopicRef: 'E2.12', ref: 'E2.12.4', name: 'Differentiation: stationary points', e_only: true },
  { subtopicRef: 'E2.12', ref: 'E2.12.5', name: 'Differentiation: maxima and minima', e_only: true },
  { subtopicRef: 'E2.13', ref: 'E2.13.1', name: 'Inverse functions', e_only: true },
  { subtopicRef: 'E2.13', ref: 'E2.13.2', name: 'Composite functions', e_only: true },
  { subtopicRef: 'E2.13', ref: 'E2.13.3', name: 'Function Machines', e_only: true },
  { subtopicRef: 'E2.13', ref: 'E2.13.4', name: 'Functions: notation, domain and range', e_only: true },
  { subtopicRef: 'C3.1', ref: 'C3.1.1', name: 'Coordinates', e_only: false },
  { subtopicRef: 'C3.1', ref: 'C3.1.2', name: 'Coordinates: shapes on a grid', e_only: false },
  { subtopicRef: 'C3.2', ref: 'C3.2.1', name: 'Linear graphs: drawing (xy table)', e_only: false },
  { subtopicRef: 'C3.2', ref: 'C3.2.2', name: 'Linear graphs: drawing using y=mx+c', e_only: false },
  { subtopicRef: 'C3.2', ref: 'C3.2.3', name: 'Linear graphs: y=a graphs', e_only: false },
  { subtopicRef: 'C3.2', ref: 'C3.2.4', name: 'Linear graphs: x=a graphs', e_only: false },
  { subtopicRef: 'C3.3', ref: 'C3.3.1', name: 'Linear graphs: gradient of a line', e_only: false },
  { subtopicRef: 'E3.4', ref: 'E3.4.1', name: 'Coordinates: distance between 2 points', e_only: true },
  { subtopicRef: 'E3.4', ref: 'E3.4.2', name: 'Coordinates: midpoint of a line', e_only: true },
  { subtopicRef: 'E3.4', ref: 'E3.4.3', name: 'Linear graphs: length of a line', e_only: true },
  { subtopicRef: 'E3.4', ref: 'E3.4.4', name: 'Linear graphs: midpoint of a line', e_only: true },
  { subtopicRef: 'C3.5', ref: 'C3.5.1', name: 'Linear graphs: y=mx+c', e_only: false },
  { subtopicRef: 'C3.5', ref: 'C3.5.2', name: 'Linear graphs: find equation of a line', e_only: false },
  { subtopicRef: 'C3.5', ref: 'C3.5.3', name: 'Linear graphs: equation through 2 points', e_only: true },
  { subtopicRef: 'C3.5', ref: 'C3.5.4', name: 'Linear graphs: x=a graphs', e_only: false },
  { subtopicRef: 'C3.5', ref: 'C3.5.5', name: 'Linear graphs: y=a graphs', e_only: false },
  { subtopicRef: 'C3.6', ref: 'C3.6.1', name: 'Linear graphs: parallel lines', e_only: false },
  { subtopicRef: 'E3.7', ref: 'E3.7.1', name: 'Linear graphs: perpendicular lines', e_only: true },
  { subtopicRef: 'E3.7', ref: 'E3.7.2', name: 'Shortest distance from point to a line', e_only: true },
  { subtopicRef: 'C4.1', ref: 'C4.1.1', name: '2D shapes: names', e_only: false },
  { subtopicRef: 'C4.1', ref: 'C4.1.2', name: '2D shapes: quadrilaterals', e_only: false },
  { subtopicRef: 'C4.1', ref: 'C4.1.3', name: '3D shapes: names', e_only: false },
  { subtopicRef: 'C4.1', ref: 'C4.1.4', name: '3D shapes: nets', e_only: false },
  { subtopicRef: 'C4.1', ref: 'C4.1.5', name: '3D shapes: vertices, edges, faces', e_only: false },
  { subtopicRef: 'C4.1', ref: 'C4.1.6', name: 'Triangles: types of', e_only: false },
  { subtopicRef: 'C4.1', ref: 'C4.1.7', name: 'Triangles: lengths of sides', e_only: false },
  { subtopicRef: 'C4.1', ref: 'C4.1.8', name: 'Circles: parts', e_only: false },
  { subtopicRef: 'C4.1', ref: 'C4.1.9', name: 'Angles: types of', e_only: false },
  { subtopicRef: 'C4.1', ref: 'C4.1.10', name: 'Angles: right angle', e_only: false },
  { subtopicRef: 'C4.1', ref: 'C4.1.11', name: 'Angles: bearings', e_only: false },
  { subtopicRef: 'C4.1', ref: 'C4.1.12', name: 'Angles: compass directions', e_only: false },
  { subtopicRef: 'C4.1', ref: 'C4.1.13', name: 'Parallel lines', e_only: false },
  { subtopicRef: 'C4.1', ref: 'C4.1.14', name: 'Perpendicular lines', e_only: false },
  { subtopicRef: 'C4.1', ref: 'C4.1.15', name: 'Congruent shapes', e_only: false },
  { subtopicRef: 'C4.1', ref: 'C4.1.16', name: 'Similar shapes: definition', e_only: false },
  { subtopicRef: 'C4.2', ref: 'C4.2.1', name: 'Angles: measuring', e_only: false },
  { subtopicRef: 'C4.2', ref: 'C4.2.2', name: 'Angles: drawing', e_only: false },
  { subtopicRef: 'C4.2', ref: 'C4.2.3', name: 'Constructions: triangles SSS', e_only: false },
  { subtopicRef: 'C4.2', ref: 'C4.2.4', name: '3D shapes: nets', e_only: false },
  { subtopicRef: 'C4.2', ref: 'C4.2.5', name: 'Constructions: ruler and compasses', e_only: false },
  { subtopicRef: 'C4.3', ref: 'C4.3.1', name: 'Scales and maps', e_only: false },
  { subtopicRef: 'C4.3', ref: 'C4.3.2', name: 'Scales: reading', e_only: false },
  { subtopicRef: 'C4.3', ref: 'C4.3.3', name: 'Angles: bearings', e_only: false },
  { subtopicRef: 'C4.3', ref: 'C4.3.4', name: 'Angles: back bearings', e_only: false },
  { subtopicRef: 'C4.3', ref: 'C4.3.5', name: 'Angles: compass directions', e_only: false },
  { subtopicRef: 'C4.3', ref: 'C4.3.6', name: 'Angles: given bearings from two points', e_only: false },
  { subtopicRef: 'C4.4', ref: 'C4.4.1', name: 'Similar shapes: definition', e_only: false },
  { subtopicRef: 'C4.4', ref: 'C4.4.2', name: 'Similar shapes: finding sides', e_only: false },
  { subtopicRef: 'C4.4', ref: 'C4.4.3', name: 'Similar shapes: area', e_only: true },
  { subtopicRef: 'C4.4', ref: 'C4.4.4', name: 'Similar shapes: volume', e_only: true },
  { subtopicRef: 'C4.4', ref: 'C4.4.5', name: 'Similar shapes: further', e_only: true },
  { subtopicRef: 'C4.5', ref: 'C4.5.1', name: 'Symmetry: line', e_only: false },
  { subtopicRef: 'C4.5', ref: 'C4.5.2', name: 'Symmetry: rotational', e_only: false },
  { subtopicRef: 'C4.6', ref: 'C4.6.1', name: 'Angles: full circle (at a point)', e_only: false },
  { subtopicRef: 'C4.6', ref: 'C4.6.2', name: 'Angles: straight line', e_only: false },
  { subtopicRef: 'C4.6', ref: 'C4.6.3', name: 'Angles: vertically opposite', e_only: false },
  { subtopicRef: 'C4.6', ref: 'C4.6.4', name: 'Angles: triangle', e_only: false },
  { subtopicRef: 'C4.6', ref: 'C4.6.5', name: 'Angles: quadrilaterals', e_only: false },
  { subtopicRef: 'C4.6', ref: 'C4.6.6', name: 'Angles: parallel lines', e_only: false },
  { subtopicRef: 'C4.6', ref: 'C4.6.7', name: 'Angles: polygons', e_only: false },
  { subtopicRef: 'C4.6', ref: 'C4.6.8', name: 'Angles: tessellations', e_only: false },
  { subtopicRef: 'C4.7', ref: 'C4.7.1', name: 'Circle theorems: theorems', e_only: false },
  { subtopicRef: 'C4.7', ref: 'C4.7.2', name: 'Circle theorems: examples', e_only: false },
  { subtopicRef: 'C4.7', ref: 'C4.7.3', name: 'Circle theorems proof: right angle semi-circle', e_only: false },
  { subtopicRef: 'C4.7', ref: 'C4.7.4', name: 'Circle theorems proof: radius and tangent', e_only: false },
  { subtopicRef: 'C4.7', ref: 'C4.7.5', name: 'Circle theorems proof: angles at circumference', e_only: true },
  { subtopicRef: 'C4.7', ref: 'C4.7.6', name: 'Circle theorems proof: angles same segment', e_only: true },
  { subtopicRef: 'C4.7', ref: 'C4.7.7', name: 'Circle theorems proof: cyclic quadrilaterals', e_only: true },
  { subtopicRef: 'C4.7', ref: 'C4.7.8', name: 'Circle theorems proof: alternate segment', e_only: true },
  { subtopicRef: 'E4.8', ref: 'E4.8.1', name: 'Circle theorems: equal chords', e_only: true },
  { subtopicRef: 'E4.8', ref: 'E4.8.2', name: 'Circle theorems: perpendicular bisector chord', e_only: true },
  { subtopicRef: 'E4.8', ref: 'E4.8.3', name: 'Circle theorems: tangents external point', e_only: true },
  { subtopicRef: 'C5.1', ref: 'C5.1.1', name: 'Units: metric and imperial', e_only: false },
  { subtopicRef: 'C5.1', ref: 'C5.1.2', name: 'Units: Metric units (length)', e_only: false },
  { subtopicRef: 'C5.1', ref: 'C5.1.3', name: 'Units: Metric units (mass)', e_only: false },
  { subtopicRef: 'C5.1', ref: 'C5.1.4', name: 'Units: Metric units (capacity)', e_only: false },
  { subtopicRef: 'C5.1', ref: 'C5.1.5', name: 'Units: converting areas', e_only: false },
  { subtopicRef: 'C5.1', ref: 'C5.1.6', name: 'Units: converting volumes', e_only: false },
  { subtopicRef: 'C5.2', ref: 'C5.2.1', name: 'Perimeter', e_only: false },
  { subtopicRef: 'C5.2', ref: 'C5.2.2', name: 'Area: rectangle', e_only: false },
  { subtopicRef: 'C5.2', ref: 'C5.2.3', name: 'Area: triangle', e_only: false },
  { subtopicRef: 'C5.2', ref: 'C5.2.4', name: 'Area: parallelogram', e_only: false },
  { subtopicRef: 'C5.2', ref: 'C5.2.5', name: 'Area: trapezium', e_only: false },
  { subtopicRef: 'C5.3', ref: 'C5.3.1', name: 'Circles: circumference', e_only: false },
  { subtopicRef: 'C5.3', ref: 'C5.3.2', name: 'Circles: area', e_only: false },
  { subtopicRef: 'C5.3', ref: 'C5.3.3', name: 'Circles: arc length', e_only: false },
  { subtopicRef: 'C5.3', ref: 'C5.3.4', name: 'Area: sector', e_only: false },
  { subtopicRef: 'C5.3', ref: 'C5.3.5', name: 'Circles: perimeter semi-circle', e_only: false },
  { subtopicRef: 'C5.3', ref: 'C5.3.6', name: 'Circles: perimeter quarter-circle', e_only: false },
  { subtopicRef: 'C5.4', ref: 'C5.4.1', name: 'Surface area: cuboid', e_only: false },
  { subtopicRef: 'C5.4', ref: 'C5.4.2', name: 'Surface area: other prisms', e_only: false },
  { subtopicRef: 'C5.4', ref: 'C5.4.3', name: 'Surface area: cylinders', e_only: false },
  { subtopicRef: 'C5.4', ref: 'C5.4.4', name: 'Surface area: sphere', e_only: false },
  { subtopicRef: 'C5.4', ref: 'C5.4.5', name: 'Surface area: cone', e_only: false },
  { subtopicRef: 'C5.4', ref: 'C5.4.6', name: 'Volume: cube/cuboid', e_only: false },
  { subtopicRef: 'C5.4', ref: 'C5.4.7', name: 'Volume: prism', e_only: false },
  { subtopicRef: 'C5.4', ref: 'C5.4.8', name: 'Volume: cylinder', e_only: false },
  { subtopicRef: 'C5.4', ref: 'C5.4.9', name: 'Volume: sphere', e_only: false },
  { subtopicRef: 'C5.4', ref: 'C5.4.10', name: 'Volume: pyramid', e_only: false },
  { subtopicRef: 'C5.4', ref: 'C5.4.11', name: 'Volume: cone', e_only: false },
  { subtopicRef: 'C5.5', ref: 'C5.5.1', name: 'Area: compound shapes', e_only: false },
  { subtopicRef: 'C5.5', ref: 'C5.5.2', name: 'Area: L-shape', e_only: false },
  { subtopicRef: 'C5.5', ref: 'C5.5.3', name: 'Area: hexagon', e_only: false },
  { subtopicRef: 'C5.5', ref: 'C5.5.4', name: 'Area: on a grid', e_only: false },
  { subtopicRef: 'C5.5', ref: 'C5.5.5', name: 'Surface area: mixture', e_only: false },
  { subtopicRef: 'C5.5', ref: 'C5.5.6', name: 'Volume: L-shape prism', e_only: false },
  { subtopicRef: 'C5.5', ref: 'C5.5.7', name: 'Volume: Frustum', e_only: true },
  { subtopicRef: 'C5.5', ref: 'C5.5.8', name: 'Surface area: frustum', e_only: true },
  { subtopicRef: 'C5.5', ref: 'C5.5.9', name: 'Circles: segment area', e_only: true },
  { subtopicRef: 'C5.5', ref: 'C5.5.10', name: 'Compound solids and parts of solids', e_only: false },
  { subtopicRef: 'C6.1', ref: 'C6.1.1', name: 'Pythagoras', e_only: false },
  { subtopicRef: 'C6.1', ref: 'C6.1.2', name: 'Pythagoras on a graph', e_only: false },
  { subtopicRef: 'C6.1', ref: 'C6.1.3', name: 'Pythagoras: distance points', e_only: true },
  { subtopicRef: 'C6.2', ref: 'C6.2.1', name: 'Trigonometry: introduction', e_only: false },
  { subtopicRef: 'C6.2', ref: 'C6.2.2', name: 'Trigonometry: missing sides', e_only: false },
  { subtopicRef: 'C6.2', ref: 'C6.2.3', name: 'Trigonometry: missing angles', e_only: false },
  { subtopicRef: 'C6.2', ref: 'C6.2.4', name: 'Pythagoras: rectangles/isosceles tri', e_only: false },
  { subtopicRef: 'C6.2', ref: 'C6.2.5', name: 'Pythagoras: show triangle is right angle', e_only: false },
  { subtopicRef: 'E6.3', ref: 'E6.3.1', name: 'Trigonometry: Exact values', e_only: true },
  { subtopicRef: 'E6.4', ref: 'E6.4.1', name: 'Trigonometry: Sine graph', e_only: true },
  { subtopicRef: 'E6.4', ref: 'E6.4.2', name: 'Trigonometry: Cosine graph', e_only: true },
  { subtopicRef: 'E6.4', ref: 'E6.4.3', name: 'Trigonometry: Tangent graph', e_only: true },
  { subtopicRef: 'E6.4', ref: 'E6.4.4', name: 'Transformations of trigonometric graphs', e_only: true },
  { subtopicRef: 'E6.5', ref: 'E6.5.1', name: 'Trigonometry: sine rule (sides)', e_only: true },
  { subtopicRef: 'E6.5', ref: 'E6.5.2', name: 'Trigonometry: sine rule (angles)', e_only: true },
  { subtopicRef: 'E6.5', ref: 'E6.5.3', name: 'Trigonometry: sine rule (ambiguous)', e_only: true },
  { subtopicRef: 'E6.5', ref: 'E6.5.4', name: 'Trigonometry: cosine rule (sides)', e_only: true },
  { subtopicRef: 'E6.5', ref: 'E6.5.5', name: 'Trigonometry: cosine rule (angles)', e_only: true },
  { subtopicRef: 'E6.5', ref: 'E6.5.6', name: 'Trigonometry: area of a triangle', e_only: true },
  { subtopicRef: 'E6.5', ref: 'E6.5.7', name: 'Trigonometry: area of triangle proof', e_only: true },
  { subtopicRef: 'E6.6', ref: 'E6.6.1', name: 'Pythagoras: 3D', e_only: true },
  { subtopicRef: 'E6.6', ref: 'E6.6.2', name: 'Trigonometry: 3D', e_only: true },
  { subtopicRef: 'C7.1', ref: 'C7.1.1', name: 'Reflections', e_only: false },
  { subtopicRef: 'C7.1', ref: 'C7.1.2', name: 'Reflections: describing', e_only: false },
  { subtopicRef: 'C7.1', ref: 'C7.1.3', name: 'Reflections: finding mirror line', e_only: false },
  { subtopicRef: 'C7.1', ref: 'C7.1.4', name: 'Rotations', e_only: false },
  { subtopicRef: 'C7.1', ref: 'C7.1.5', name: 'Translations: vector', e_only: false },
  { subtopicRef: 'C7.1', ref: 'C7.1.6', name: 'Translations: describing', e_only: false },
  { subtopicRef: 'C7.1', ref: 'C7.1.7', name: 'Enlargements', e_only: false },
  { subtopicRef: 'C7.1', ref: 'C7.1.8', name: 'Enlargements: centre of enlargement', e_only: false },
  { subtopicRef: 'C7.1', ref: 'C7.1.9', name: 'Enlargements: describing', e_only: false },
  { subtopicRef: 'C7.1', ref: 'C7.1.10', name: 'Enlargements: finding centre', e_only: false },
  { subtopicRef: 'C7.1', ref: 'C7.1.11', name: 'Enlargements: fractional scale factor', e_only: false },
  { subtopicRef: 'C7.1', ref: 'C7.1.12', name: 'Enlargements: negative scale factor', e_only: true },
  { subtopicRef: 'C7.1', ref: 'C7.1.13', name: 'Enlargements: ray method', e_only: false },
  { subtopicRef: 'C7.1', ref: 'C7.1.14', name: 'Transformations: mixture', e_only: false },
  { subtopicRef: 'E7.2', ref: 'E7.2.1', name: 'Vectors', e_only: true },
  { subtopicRef: 'E7.2', ref: 'E7.2.2', name: 'Vectors: Column', e_only: true },
  { subtopicRef: 'E7.2', ref: 'E7.2.3', name: 'Translations: vector', e_only: true },
  { subtopicRef: 'E7.3', ref: 'E7.3.1', name: 'Vectors: magnitude', e_only: true },
  { subtopicRef: 'E7.4', ref: 'E7.4.1', name: 'Vector geometry', e_only: true },
  { subtopicRef: 'E7.4', ref: 'E7.4.2', name: 'Invariant Points', e_only: true },
  { subtopicRef: 'C8.1', ref: 'C8.1.1', name: 'Probability: basic', e_only: false },
  { subtopicRef: 'C8.1', ref: 'C8.1.2', name: 'Probability: scale', e_only: false },
  { subtopicRef: 'C8.1', ref: 'C8.1.3', name: 'Probability: not happening', e_only: false },
  { subtopicRef: 'C8.2', ref: 'C8.2.1', name: 'Probability: relative frequency', e_only: false },
  { subtopicRef: 'C8.2', ref: 'C8.2.2', name: 'Probability: expected frequency', e_only: false },
  { subtopicRef: 'C8.2', ref: 'C8.2.3', name: 'Sampling: random', e_only: false },
  { subtopicRef: 'C8.3', ref: 'C8.3.1', name: 'Probability: sample space', e_only: false },
  { subtopicRef: 'C8.3', ref: 'C8.3.2', name: 'Probability: tree diagrams', e_only: false },
  { subtopicRef: 'C8.3', ref: 'C8.3.3', name: 'Probability: listing outcomes', e_only: false },
  { subtopicRef: 'C8.3', ref: 'C8.3.4', name: 'Probability: OR rule', e_only: false },
  { subtopicRef: 'C8.3', ref: 'C8.3.5', name: 'Venn Diagrams', e_only: false },
  { subtopicRef: 'E8.4', ref: 'E8.4.1', name: 'Probability: conditional', e_only: true },
  { subtopicRef: 'E8.4', ref: 'E8.4.2', name: 'Probability: independent events', e_only: true },
  { subtopicRef: 'E8.4', ref: 'E8.4.3', name: 'Probability: tree diagrams', e_only: true },
  { subtopicRef: 'C9.1', ref: 'C9.1.1', name: 'Types of data: Qualitative/Quantitative', e_only: false },
  { subtopicRef: 'C9.1', ref: 'C9.1.2', name: 'Types of data: discrete and continuous', e_only: false },
  { subtopicRef: 'C9.1', ref: 'C9.1.3', name: 'Types of data: primary and secondary', e_only: false },
  { subtopicRef: 'C9.1', ref: 'C9.1.4', name: 'Tally charts', e_only: false },
  { subtopicRef: 'C9.1', ref: 'C9.1.5', name: 'Tables: two-way tables', e_only: false },
  { subtopicRef: 'C9.1', ref: 'C9.1.6', name: 'Reading Tables', e_only: false },
  { subtopicRef: 'C9.2', ref: 'C9.2.1', name: 'Data handling cycle', e_only: false },
  { subtopicRef: 'C9.2', ref: 'C9.2.2', name: 'Questionnaires', e_only: false },
  { subtopicRef: 'C9.2', ref: 'C9.2.3', name: 'Sampling: using samples', e_only: false },
  { subtopicRef: 'C9.2', ref: 'C9.2.4', name: 'Sampling: stratified', e_only: true },
  { subtopicRef: 'C9.2', ref: 'C9.2.5', name: 'Graphs: box plots draw/interpret', e_only: true },
  { subtopicRef: 'C9.2', ref: 'C9.2.6', name: 'Graphs: box plots compare', e_only: true },
  { subtopicRef: 'C9.2', ref: 'C9.2.7', name: 'Statistics: comparing data sets', e_only: false },
  { subtopicRef: 'C9.3', ref: 'C9.3.1', name: 'Averages: mean', e_only: false },
  { subtopicRef: 'C9.3', ref: 'C9.3.2', name: 'Averages: median', e_only: false },
  { subtopicRef: 'C9.3', ref: 'C9.3.3', name: 'Averages: mode', e_only: false },
  { subtopicRef: 'C9.3', ref: 'C9.3.4', name: 'Averages: range', e_only: false },
  { subtopicRef: 'C9.3', ref: 'C9.3.5', name: 'Averages: mean (frequency table)', e_only: false },
  { subtopicRef: 'C9.3', ref: 'C9.3.6', name: 'Averages: median (frequency table)', e_only: false },
  { subtopicRef: 'C9.3', ref: 'C9.3.7', name: 'Averages: mode (frequency table)', e_only: false },
  { subtopicRef: 'C9.3', ref: 'C9.3.8', name: 'Averages: range (frequency tables)', e_only: false },
  { subtopicRef: 'C9.3', ref: 'C9.3.9', name: 'Averages: combined mean', e_only: true },
  { subtopicRef: 'C9.3', ref: 'C9.3.10', name: 'Averages: Quartiles', e_only: true },
  { subtopicRef: 'C9.3', ref: 'C9.3.11', name: 'Averages: class containing median', e_only: true },
  { subtopicRef: 'C9.3', ref: 'C9.3.12', name: 'Averages: median (grouped data)', e_only: true },
  { subtopicRef: 'C9.3', ref: 'C9.3.13', name: 'Averages: mean (estimated)', e_only: true },
  { subtopicRef: 'C9.3', ref: 'C9.3.14', name: 'Averages: Distributions', e_only: true },
  { subtopicRef: 'C9.4', ref: 'C9.4.1', name: 'Graphs: bar charts (draw)', e_only: false },
  { subtopicRef: 'C9.4', ref: 'C9.4.2', name: 'Graphs: bar charts (reading)', e_only: false },
  { subtopicRef: 'C9.4', ref: 'C9.4.3', name: 'Graphs: composite bar charts', e_only: false },
  { subtopicRef: 'C9.4', ref: 'C9.4.4', name: 'Graphs: dual bar charts', e_only: false },
  { subtopicRef: 'C9.4', ref: 'C9.4.5', name: 'Graphs: pie charts (draw)', e_only: false },
  { subtopicRef: 'C9.4', ref: 'C9.4.6', name: 'Graphs: pie charts (interpret)', e_only: false },
  { subtopicRef: 'C9.4', ref: 'C9.4.7', name: 'Graphs: pictograms (draw)', e_only: false },
  { subtopicRef: 'C9.4', ref: 'C9.4.8', name: 'Graphs: pictograms (interpret)', e_only: false },
  { subtopicRef: 'C9.4', ref: 'C9.4.9', name: 'Graphs: stem and leaf (draw)', e_only: false },
  { subtopicRef: 'C9.4', ref: 'C9.4.10', name: 'Graphs: stem and leaf (interpret)', e_only: false },
  { subtopicRef: 'C9.4', ref: 'C9.4.11', name: 'Frequency tables', e_only: false },
  { subtopicRef: 'C9.5', ref: 'C9.5.1', name: 'Graphs: scatter graphs (draw)', e_only: false },
  { subtopicRef: 'C9.5', ref: 'C9.5.2', name: 'Graphs: scatter graphs (interpret)', e_only: false },
  { subtopicRef: 'C9.5', ref: 'C9.5.3', name: 'Graphs: scatter graphs (line of best fit)', e_only: false },
  { subtopicRef: 'C9.5', ref: 'C9.5.4', name: 'Graphs: scatter graphs (correlation)', e_only: false },
  { subtopicRef: 'E9.6', ref: 'E9.6.1', name: 'Graphs: cumulative frequency (draw)', e_only: true },
  { subtopicRef: 'E9.6', ref: 'E9.6.2', name: 'Graphs: cumulative frequency (reading)', e_only: true },
  { subtopicRef: 'E9.6', ref: 'E9.6.3', name: 'Graphs: box plots draw/interpret', e_only: true },
  { subtopicRef: 'E9.6', ref: 'E9.6.4', name: 'Graphs: box plots compare', e_only: true },
  { subtopicRef: 'E9.7', ref: 'E9.7.1', name: 'Graphs: histograms (draw)', e_only: true },
  { subtopicRef: 'E9.7', ref: 'E9.7.2', name: 'Graphs: histograms (interpret)', e_only: true },
  { subtopicRef: 'E9.7', ref: 'E9.7.3', name: 'Graphs: histograms harder', e_only: true },
  { subtopicRef: 'E9.7', ref: 'E9.7.4', name: 'Graphs: frequency polygons (draw)', e_only: true },
  { subtopicRef: 'E9.7', ref: 'E9.7.5', name: 'Graphs: frequency polygons (reading)', e_only: true },
]

async function seed() {
  console.log('Starting hierarchy seed...')
  const { data: allTopics } = await supabase.from('topics').select('id, name, code')
  const topicByCode = new Map(allTopics?.map(t => [t.code, t.id]) ?? [])
  if (!topicByCode.size) { console.error('No topics found — run migration first'); process.exit(1) }

  if (!topicByCode.has('MIX')) {
    const { data: mt } = await supabase.from('topics').insert({ name: 'Mix Topics', code: 'MIX' }).select('id').single()
    if (mt) topicByCode.set('MIX', mt.id)
    console.log('  ✅ Added: Mix Topics')
  }

  const { data: refreshed } = await supabase.from('topics').select('id, code')
  const topicIdByCode = new Map(refreshed?.map(t => [t.code, t.id]) ?? [])

  const { data: existingSubs } = await supabase.from('subtopics').select('id, name, code')
  const subByCode = new Map(existingSubs?.map(s => [s.code, s]) ?? [])
  const subByName = new Map(existingSubs?.map(s => [s.name.toLowerCase().trim(), s]) ?? [])
  let updated = 0, inserted = 0

  for (const sub of SUBTOPICS) {
    const topicNum = sub.ref.slice(1).split('.')[0]
    const topicId = topicIdByCode.get('C' + topicNum)
    if (!topicId) { console.warn('  ⚠️ No topic for', sub.ref); continue }
    const existing = subByCode.get(sub.ref) || subByName.get(sub.name.toLowerCase().trim())
    if (existing) {
      await supabase.from('subtopics').update({ code: sub.ref, e_only: sub.e_only }).eq('id', existing.id)
      subByCode.set(sub.ref, { ...existing, code: sub.ref })
      updated++
    } else {
      const { data: ns } = await supabase.from('subtopics').insert({ topic_id: topicId, name: sub.name, code: sub.ref, e_only: sub.e_only }).select('id').single()
      if (ns) subByCode.set(sub.ref, { id: ns.id, code: sub.ref, name: sub.name })
      inserted++
    }
  }

  if (!existingSubs?.some(s => s.name === 'Mix Subtopics')) {
    const mixId = topicIdByCode.get('MIX')
    if (mixId) { await supabase.from('subtopics').insert({ topic_id: mixId, name: 'Mix Subtopics', code: 'MIX', e_only: false }); console.log('  ✅ Added: Mix Subtopics') }
  }
  console.log(`  Subtopics: ${updated} updated, ${inserted} inserted`)

  const { data: allSubs } = await supabase.from('subtopics').select('id, code')
  const subIdByCode = new Map(allSubs?.map(s => [s.code, s.id]) ?? [])
  await supabase.from('sub_subtopics').delete().neq('id', '00000000-0000-0000-0000-000000000000')

  const valid = SUB_SUBTOPICS.filter(ss => subIdByCode.has(ss.subtopicRef))
  let totalInserted = 0
  for (let i = 0; i < valid.length; i += 100) {
    const rows = valid.slice(i, i + 100).map(ss => ({ subtopic_id: subIdByCode.get(ss.subtopicRef), ref: ss.ref, name: ss.name, e_only: ss.e_only }))
    const { error } = await supabase.from('sub_subtopics').insert(rows)
    if (error) console.warn('  ⚠️ Insert error:', error.message)
    else totalInserted += rows.length
  }
  console.log(`  Sub-subtopics inserted: ${totalInserted}`)

  const { count: tc } = await supabase.from('topics').select('*', { count: 'exact', head: true })
  const { count: sc } = await supabase.from('subtopics').select('*', { count: 'exact', head: true })
  const { count: ssc } = await supabase.from('sub_subtopics').select('*', { count: 'exact', head: true })
  console.log('\n=== FINAL COUNTS ===')
  console.log(`  topics:        ${tc}  (expected: 10)`)
  console.log(`  subtopics:     ${sc}  (expected: 73+)`)
  console.log(`  sub_subtopics: ${ssc} (expected: 453)`)
  console.log('✅ Done!')
}
seed().catch(console.error)
